name: BBB
on:
    # push:
    #     branches:
    #         - master
    workflow_dispatch:
    schedule:
        - cron: "0 0-15/2 * * *"
jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout codes
              uses: actions/checkout@v2
            - name: Use Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: "12.x"
            - name: Run app
              run: npm install
            - run: node BBB/BBB.js
              env:
                  bbb_ck: ${{ secrets.bbb_ck }}