name: day

on:
  workflow_dispatch:
  schedule:
    - cron: '0 16 * * *'

jobs:
  build:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: set-time
      run: sudo timedatectl set-timezone 'Asia/Shanghai'

    - name: Node.JS
      uses: actions/setup-node@v1
      with:
        node-version: 12
        registry-url: "https://registry.npmjs.org"

    - name: Python3
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: dependencies
      run: |
        cd function/
        npm install
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: tasks
      env:
        PHONE: ${{ secrets.PHONE }}
        PASSWORD: ${{ secrets.PASSWORD }}
        SCKEY: ${{ secrets.BARK_PUSH }}
      run: python3 function/music.py ${PHONE} ${PASSWORD} -s ${SCKEY}

    - name: tasks
      run: node function/tieba.js
      env:
                  BILI_USER: ${{ secrets.BILI_USER }}
                  BILI_PASS: ${{ secrets.BILI_PASS }}
                  BILI_COOKIE: ${{ secrets.BILI_COOKIE }}
                  BILI_NUM: ${{ secrets.BILI_NUM }}
                  BILI_TYPE: ${{ secrets.BILI_TYPE }}
                  SEND_KEY: ${{ secrets.SEND_KEY }}
                  PUSH_KEY: ${{ secrets.PUSH_KEY }}
                  BARK_PUSH: ${{ secrets.BARK_PUSH }}
                  PUSH_PLUS_TOKEN: ${{ secrets.PUSH_PLUS_TOKEN}}
                  PUSH_PLUS_USER: ${{ secrets.PUSH_PLUS_USER}}
                  TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
                  TG_USER_ID: ${{ secrets.TG_USER_ID }}
                  BARK_SOUND: ${{ secrets.BARK_SOUND }}
                  DD_BOT_TOKEN: ${{ secrets.DD_BOT_TOKEN }}
                  DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET }}

    - name: tasks
      run: node function/v_video.js
      env:
                  V_REF_URL: ${{ secrets.V_REF_URL }}
                  V_COOKIE: ${{ secrets.V_COOKIE }}
                  SEND_KEY: ${{ secrets.SEND_KEY }}
                  PUSH_KEY: ${{ secrets.PUSH_KEY }}
                  BARK_PUSH: ${{ secrets.BARK_PUSH }}
                  PUSH_PLUS_TOKEN: ${{ secrets.PUSH_PLUS_TOKEN}}
                  PUSH_PLUS_USER: ${{ secrets.PUSH_PLUS_USER}}
                  QYWX_KEY: ${{ secrets.QYWX_KEY}}
                  QYWX_AM: ${{ secrets.QYWX_AM}}
                  TG_PROXY_HOST: ${{ secrets.TG_PROXY_HOST}}
                  TG_PROXY_PORT: ${{ secrets.TG_PROXY_PORT}}
                  IGOT_PUSH_KEY: ${{ secrets.IGOT_PUSH_KEY}}
                  TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
                  TG_USER_ID: ${{ secrets.TG_USER_ID }}
                  BARK_SOUND: ${{ secrets.BARK_SOUND }}
                  DD_BOT_TOKEN: ${{ secrets.DD_BOT_TOKEN }}
                  DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET }}
