name: day

on:
  workflow_dispatch:
  schedule:
    - cron: '0 9,16 * * *'

jobs:
  build:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: 【设置服务时区】
      run: sudo timedatectl set-timezone 'Asia/Shanghai'

    - name: 【设置Node.JS】
      uses: actions/setup-node@v1
      with:
        node-version: 12
        registry-url: "https://registry.npmjs.org"

    - name: 【设置Python3】
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: 【安装所需依赖】
      run: |
        cd function/
        npm install

    - name: 【安装所需依赖】
      run: |
        python -m pip install --upgrade pip
        cd function/
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: 【网易日常任务】
      env:
        PHONE: ${{ secrets.PHONE }}
        PASSWORD: ${{ secrets.PASSWORD }}
        SCKEY: ${{ secrets.BARK_PUSH }}
      run: python3 function/music.py ${PHONE} ${PASSWORD} -s ${SCKEY}

    - name: 【百度签到任务】
      run: node function/tieba.js
      env:
        BDUSS: ${{ secrets.BDUSS }}
        BARK_PUSH: ${{ secrets.BARK_PUSH }}


    - name: 【腾讯视频签到】
      run: node function/v_video.js
      env:
        V_REF_URL: ${{ secrets.V_REF_URL }}
        V_COOKIE: ${{ secrets.V_COOKIE }}
        BARK_PUSH: ${{ secrets.BARK_PUSH }}

