name: emmm

on:
  workflow_dispatch: 
  schedule: 
    - cron: '0 0,8 * * *'

jobs:
  build:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: set-timezone
      run: sudo timedatectl set-timezone 'Asia/Shanghai'

    - name: Node.JS
      uses: actions/setup-node@v1
      with:
        node-version: 12
        registry-url: "https://registry.npmjs.org"
        
    - name: dependencies
      env:
        GISTENV: ${{secrets.GISTENV}}
      run: |
        git clone -b azmodan https://github.com/DJ-clamp/BaseSation.git ~/task
        cd ~/task
        npm install
        sed -i $(echo `sed -n '/process.env.GITHUB_ACTIONS/=' utils/scheduler.js`+1|bc)d utils/scheduler.js
        wget -c ${GISTENV} -O config/.env

    - name: run
      run: |
        cd ~/task && node index.js unicom  --tryrun --tasks $(cat ~/task/commands/tasks/unicom/unicom.js | sed '/\/\*\*\*/,/\*\*\*\//d' | sed '/\/\//d' | grep -oE "\"[a-z A-Z0-9]+\"" | cut -f2 -d\" | tr "\n" ",")
