name: 京东疯狂JOY挂机

on:
    workflow_dispatch:
   # schedule:
       # - cron: "0 1-23/5 * * *"
    watch:
        types: [started]
    repository_dispatch:
        types: jd_crazy_joy_coin

jobs:
    build:
        runs-on: ubuntu-latest
        if: github.event.repository.owner.id == github.event.sender.id
        steps:
            - name: 拉取代码
              uses: actions/checkout@v2
            - name: Use Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: "12.x"
            - name: 安装依赖包
              run: |
                  npm install
            - name: "运行【京东疯狂JOY挂机】"
              run: |
                  node function/jd_crazy_joy_coin.js
              env:
                  JD_COOKIE: ${{ github.event.client_payload.JD_COOKIE || secrets.JD_COOKIE }}
                  
