name: run

on:
  workflow_dispatch:


jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v2

      - name: run
        env:
         PARAMETER: ${{ secrets.PARAMETER }}
        run: |
         bash function/CnUnicom.sh $PARAMETER
