name: My-BBBTask
on:
    workflow_dispatch:
    schedule:
        - cron: "0 0-15/2 * * *"
jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout codes
              uses: actions/checkout@v2
            - name: Use Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: "12.x"
            - name: Cache node_modules
              uses: actions/cache@v2
              env:
                cache-name: cache-node-modules
              with:
                path: node_modules
                key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('package.json') }}
            - name: Run app
              run:  npm install
            - name: Run node
              run: node function/BBB.js 