name: NieJI-Task

on:
  workflow_dispatch: # 手动触发
  schedule: # 计划任务触发
    - cron: "0 1,6,12,16 * * *" # cron表达式，Actions时区是UTC时间，所以要往前推8个小时,如上表示每天13点10分

jobs:
  build:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: 【设置服务时区】
      run: sudo timedatectl set-timezone 'Asia/Shanghai'

    - name: 【设置Node.JS】
      uses: actions/setup-node@v1
      with:
        node-version: 12
        registry-url: "https://registry.npmjs.org"

    - name: 【安装所需依赖】
      run: |
        npm install

    - name: 【联通日常任务】
      env:
        usernj: ${{secrets.unicom_usernj}}
        passwordnj: ${{secrets.unicom_passwordnj}}
        appidnj: ${{secrets.unicom_appidnj}}
      run: node index.js unicom --user=${usernj} --password=${passwordnj} --appid=${appidnj} --tryrun
