name: NieJI-Task

on:
  workflow_dispatch: 
  schedule: 
    - cron: '0 0,8,16 * * *'

jobs:
  build:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: 【设置服务时区】
      run: sudo timedatectl set-timezone 'Asia/Shanghai'

    - name: 【设置Node.JS】
      uses: actions/setup-node@v1
      with:
        node-version: 12
        registry-url: "https://registry.npmjs.org"

    - name: 【安装所需依赖】
      run: |
        npm install

    - name: 【联通日常任务】
      env:
        usernj: ${{secrets.UNICOM_USERNJ}}
        passwordnj: ${{secrets.UNICOM_PASSWORDNJ}}
        appidnj: ${{secrets.UNICOM_APPIDNJ}}
      run: node index.js unicom --user ${usernj} --password ${passwordnj} --appid ${appidnj} --tryrun
