name: emmm

on:
  workflow_dispatch: 
  schedule: 
    - cron: '0 1,9,13,17,21 * * *'

jobs:
  build:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: 【设置服务时区】
      run: sudo timedatectl set-timezone 'Asia/Shanghai'

    - name: 【设置Node.JS】
      uses: actions/setup-node@v1
      with:
        node-version: 12
        registry-url: "https://registry.npmjs.org"
        
    - name: 【安装所需依赖】
      run: |
        git clone -b azmodan https://github.com/DJ-clamp/BaseSation.git ~/task
        cd ~/task && npm install && sed -i $(echo `sed -n '/process.env.GITHUB_ACTIONS/=' utils/scheduler.js`+1|bc)d utils/scheduler.js

    - name: 【联通日常任务1】
      env:
        user: ${{secrets.unicom_user}}
        password: ${{secrets.unicom_password}}
        appid: ${{secrets.unicom_appid}}
      run: cd ~/task && node index.js unicom --user=${user} --password=${password} --appid=${appid} --tryrun
    - name: 【联通日常任务2】
      env:
        usernj: ${{secrets.UNICOM_USERNJ}}
        passwordnj: ${{secrets.UNICOM_PASSWORDNJ}}
        appidnj: ${{secrets.UNICOM_APPIDNJ}}
      run: cd ~/task && node index.js unicom --user ${usernj} --password ${passwordnj} --appid ${appidnj} --tryrun
