name: unicom
on:
  workflow_dispatch:
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout codebase
      uses: actions/checkout@v2
    - name: 【联通掌厅签到】
      env:
        RUSH: ${{ secrets.RUSH }}
      run: bash function/CnUnicom.sh $RUSH
