name: unicom
on:
  workflow_dispatch:
  schedule:
    - cron: '5 16 * * *'

jobs:
  build:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: 【设置服务时区】
      run: sudo timedatectl set-timezone 'Asia/Shanghai'


    - name: 【设置Python3】
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: 【安装所需依赖】
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi


    - name: 【联通掌厅签到】
      env:
        user: ${{ secrets.USER }}
        appid: ${{ secrets.APPID }}
      run: |
            if test -z "$appid"; then   appid="247b001385de5cc6ce11731ba1b15835313d489d604e58280e455a6c91e5058651acfb0f0b77029c2372659c319e02645b54c0acc367e692ab24a546b83c302d"; fi
            
            for u in $user
            do
              bash function/CnUnicom.sh ${u/,/ }
            done
