name: unicom
on:
  workflow_dispatch:
jobs:
  build:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: 【设置服务时区】
      run: sudo timedatectl set-timezone 'Asia/Shanghai'

    - name: 【联通掌厅签到】
      env:
        user: ${{ secrets.USER }}
        appid: ${{ secrets.APPID }}
      run: bash function/CnUnicom.sh githubaction membercenter ${user}
